models_tested_with_succes = {
								"casperhansen/llama-3-70b-instruct-awq": 				{"tensor_parallel_size": 4},
								"hugging-quants/Meta-Llama-3.1-70B-Instruct-AWQ-INT4":	{"tensor_parallel_size": 4, "max_model_len": 24000, "max_num_seqs": 32},
								"MaziyarPanahi/Mixtral-8x22B-Instruct-v0.1-AWQ":		{"tensor_parallel_size": 4, "max_model_len": 20000, "max_num_seqs": 32, "gpu_memory_utilization": 1, "enforce_eager": "True"},
								"ybelkada/Mixtral-8x7B-Instruct-v0.1-AWQ":				{"tensor_parallel_size": 4},
								"TheBloke/Mixtral-8x7B-Instruct-v0.1-GPTQ":				{"tensor_parallel_size": 4, "revision": "gptq-8bit--1g-actorder_True"},
								"mistral-community/Mistral-7B-Instruct-v0.3":			{"tensor_parallel_size": 1, "max_model_len": 24000},
								"meta-llama/Meta-Llama-3.1-8B-Instruct":				{"tensor_parallel_size": 1, "max_model_len": 20000}
							}

questions = [	"Who won the World Cup in 2022?",
				"Where are a dog's sweat glands located?",
				"Who narrates the adventures of Sherlock Holmes?",
				"Who was the fortieth president of the USA?",
				"What does Bistro mean in Russian?",
				"How many nautical miles are there in one degree of latitude?",
				"Who founded the French Academy?",
				"What is the longest river in Western Europe?",
				"Who is inseparable from Bonnie Parker?",
				"What is the northern slope of a valley called?",
				"Who is the Sun God in ancient Egypt?",
				"What is the name of the doctor in Cluedo?",
				"What is the capital of Bermuda?",
				"What was the first name of the game of bowls?",
				"Which being walks on 4 legs in the morning, 2 at lunchtime and 3 in the evening?",
				"How long does it take for the Earth to revolve around the Sun?",
				"In which country are Afrikaans and English spoken?",
				"Which city built the first metro?",
				"Who first set foot on the Moon?",
				"Which of the five senses does the snake lack?",
				"What does the penguin eat?",
				"What openings do fish and violins have in common?",
				"On which continent is Adélie Land located?",
				"What does a conchyophile collect?",
				"Where are the most expensive seats in a bullfight arena?",
				"Where was Wolfgang Amadeus Mozart born?",
				"Which people invented gunpowder?",
				"What are Rubens first names?",
				"Which river has the largest flow in the world?",
				"How many players are there on the field on a baseball team?",
				"What do you call a boat with three hulls?",
				"What does a seringueiro harvest in Brazil?",
				"Who is The Magnificent”?",
				"Who is the heroine of Notre-Dame de Paris?",
				"Which capital stands at the confluence of the Blue Nile and the White Nile?",
				"Who had tiny tootsies?",
				"On which side of the plate should the wine glass be placed?"
			]